const CACHE = "nugget-realms-v140";
const ASSETS = [
  "./",
  "./index.html",
  "./styles.css",
  "./src/game.js",
  "./manifest.webmanifest",
  "./assets/art/realm-background-atlas.png",
  "./assets/art/enemy-encounter-atlas.png",
  "./assets/art/enemy-sprite-atlas.png",
  "./assets/art/winged-treasure-chest.png",
  "./assets/art/winged-treasure-chest-clean.png",
  "./assets/art/flying-diamond-spin.png",
  "./assets/art/flying-diamond-spin-clean.png",
  "./assets/art/shop-diamond-icon.png",
  "./assets/art/gold-nugget-icon.png",
  "./assets/art/ether-icon.png",
  "./assets/art/tap-gavel.png",
  "./assets/art/green-flame.png",
  "./assets/art/righteous-hammer-atlas.png",
  "./assets/art/righteous-hammer-strike.png",
  "./assets/art/righteous-hammer-icon.png",
  "./assets/art/zone-level-icons-atlas.png",
  "./assets/art/zone-level-mossglow.png",
  "./assets/art/zone-level-emberglass.png",
  "./assets/art/zone-level-frostvein.png",
  "./assets/art/zone-level-moonlit.png",
  "./assets/art/zone-level-stormforge.png",
  "./assets/art/zone-level-starfall.png",
  "./assets/gear/hd/emberglass-chest.png",
  "./assets/gear/hd/emberglass-gloves.png",
  "./assets/gear/hd/emberglass-helm.png",
  "./assets/gear/hd/emberglass-legs.png",
  "./assets/gear/hd/empty-chest.png",
  "./assets/gear/hd/empty-gloves.png",
  "./assets/gear/hd/empty-helm.png",
  "./assets/gear/hd/empty-legs.png",
  "./assets/gear/hd/frostvein-chest.png",
  "./assets/gear/hd/frostvein-gloves.png",
  "./assets/gear/hd/frostvein-helm.png",
  "./assets/gear/hd/frostvein-legs.png",
  "./assets/gear/hd/gear-atlas-source.png",
  "./assets/gear/hd/moonlit-chest.png",
  "./assets/gear/hd/moonlit-gloves.png",
  "./assets/gear/hd/moonlit-helm.png",
  "./assets/gear/hd/moonlit-legs.png",
  "./assets/gear/hd/mossglow-chest.png",
  "./assets/gear/hd/mossglow-gloves.png",
  "./assets/gear/hd/mossglow-helm.png",
  "./assets/gear/hd/mossglow-legs.png",
  "./assets/gear/hd/starfall-chest.png",
  "./assets/gear/hd/starfall-gloves.png",
  "./assets/gear/hd/starfall-helm.png",
  "./assets/gear/hd/starfall-legs.png",
  "./assets/gear/hd/stormforge-chest.png",
  "./assets/gear/hd/stormforge-gloves.png",
  "./assets/gear/hd/stormforge-helm.png",
  "./assets/gear/hd/stormforge-legs.png",
  "./assets/gear/emberglass-chest.svg",
  "./assets/gear/emberglass-gloves.svg",
  "./assets/gear/emberglass-helm.svg",
  "./assets/gear/emberglass-legs.svg",
  "./assets/gear/empty-chest.svg",
  "./assets/gear/empty-gloves.svg",
  "./assets/gear/empty-helm.svg",
  "./assets/gear/empty-legs.svg",
  "./assets/gear/frostvein-chest.svg",
  "./assets/gear/frostvein-gloves.svg",
  "./assets/gear/frostvein-helm.svg",
  "./assets/gear/frostvein-legs.svg",
  "./assets/gear/moonlit-chest.svg",
  "./assets/gear/moonlit-gloves.svg",
  "./assets/gear/moonlit-helm.svg",
  "./assets/gear/moonlit-legs.svg",
  "./assets/gear/mossglow-chest.svg",
  "./assets/gear/mossglow-gloves.svg",
  "./assets/gear/mossglow-helm.svg",
  "./assets/gear/mossglow-legs.svg",
  "./assets/gear/starfall-chest.svg",
  "./assets/gear/starfall-gloves.svg",
  "./assets/gear/starfall-helm.svg",
  "./assets/gear/starfall-legs.svg",
  "./assets/gear/stormforge-chest.svg",
  "./assets/gear/stormforge-gloves.svg",
  "./assets/gear/stormforge-helm.svg",
  "./assets/gear/stormforge-legs.svg",
  "./assets/audio/Frost.wav",
  "./assets/audio/Mossglow Path.wav",
  "./assets/audio/Frostbite Idle Run.wav",
  "./assets/audio/Swamp.wav",
  "./assets/audio/Orbital Idle Run.wav",
  "./assets/audio/Boss.wav",
  "./assets/upgrade-icons.png",
  "./assets/icons/fantasy-upgrade-atlas.png",
  "./assets/icons/buff-offer-atlas.png",
  "./assets/icons/buff-offer-atlas-square.png",
  "./assets/icons/bag-reset-atlas.png",
  "./assets/icons/inventory-backpack-icon.png",
  "./assets/icons/hammer-reset-icon.png",
  "./assets/icons/prospector-pick.png",
  "./assets/icons/clockwork-miner.png",
  "./assets/icons/adventurer-guild.png",
  "./assets/icons/alchemist-vial.png",
  "./assets/icons/diamond-drill.png",
  "./assets/icons/royal-treasury.png",
  "./assets/icons/battle-standard.png",
  "./assets/icons/astral-compass.png",
  "./assets/icons/prospector-pick.svg",
  "./assets/icons/clockwork-miner.svg",
  "./assets/icons/adventurer-guild.svg",
  "./assets/icons/crit-charm.svg",
  "./assets/icons/alchemist-vial.svg",
  "./assets/icons/diamond-drill.svg",
  "./assets/icons/royal-treasury.svg",
  "./assets/icons/battle-standard.svg",
  "./assets/icons/astral-compass.svg"
];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
  );
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  event.respondWith(caches.match(event.request).then((cached) => cached || fetch(event.request)));
});
